import { Tenant } from "@/context/TenantContext/types";

export const mockTenants: Tenant[] = [
  {
    id: "nike-slots",
    name: "Nike Slots",
    ownerUid: "owner-1",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#111111",
      logoUrl: "https://via.placeholder.com/120x60?text=Nike",
    },
    settings: { cooldownMs: 2000 },
    affiliate: "nike-aff",
    createdAt: new Date().toISOString(),
  },
  {
    id: "adidas-spin",
    name: "Adidas Spin",
    ownerUid: "owner-2",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#0a0a0a",
      logoUrl: "https://via.placeholder.com/120x60?text=Adidas",
    },
    settings: { cooldownMs: 1500 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "amazon-jackpot",
    name: "Amazon Jackpot",
    ownerUid: "owner-3",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#ff9900",
      logoUrl: "https://via.placeholder.com/120x60?text=Amazon",
    },
    settings: { cooldownMs: 1000 },
    affiliate: "amz-aff",
    createdAt: new Date().toISOString(),
  },
  {
    id: "tech-world",
    name: "Tech World Slots",
    ownerUid: "owner-4",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#0066ff",
      logoUrl: "https://via.placeholder.com/120x60?text=Tech",
    },
    settings: { cooldownMs: 3000 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "gamer-zone",
    name: "Gamer Zone",
    ownerUid: "owner-5",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#8e44ad",
      logoUrl: "https://via.placeholder.com/120x60?text=Gamer",
    },
    settings: { cooldownMs: 1800 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "fashion-spin",
    name: "Fashion Spin",
    ownerUid: "owner-6",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#e91e63",
      logoUrl: "https://via.placeholder.com/120x60?text=Fashion",
    },
    settings: { cooldownMs: 2500 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "crypto-rewards",
    name: "Crypto Rewards",
    ownerUid: "owner-7",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#f39c12",
      logoUrl: "https://via.placeholder.com/120x60?text=Crypto",
    },
    settings: { cooldownMs: 900 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "travel-spin",
    name: "Travel Spin",
    ownerUid: "owner-8",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#16a085",
      logoUrl: "https://via.placeholder.com/120x60?text=Travel",
    },
    settings: { cooldownMs: 2200 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "beauty-jackpot",
    name: "Beauty Jackpot",
    ownerUid: "owner-9",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#d35400",
      logoUrl: "https://via.placeholder.com/120x60?text=Beauty",
    },
    settings: { cooldownMs: 1100 },
    createdAt: new Date().toISOString(),
  },
  {
    id: "super-market-spin",
    name: "Super Market Spin",
    ownerUid: "owner-10",
    status: "active",
    subscriptionMode: "tenantPremium",
    branding: {
      primaryColor: "#2ecc71",
      logoUrl: "https://via.placeholder.com/120x60?text=Market",
    },
    settings: { cooldownMs: 1700 },
    createdAt: new Date().toISOString(),
  },
];
